# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages


# Course-site specific configuration:
course:
  # Enter a base path if needed; not necessary for testing at localhost:4000/
  # or if your site is hosted at a simple URL like http://example.com/
  # But, if something comes after the .com/, you should enter it here.
  # E.g., for http://example.com/530/ you'd enter 530/ for base_path:
  base_path: fall-2017
  # E.g., ENGL 536
  number: ENGCMP 610
  name: Composing Digital Media
  # Keep the description brief, about 140 chars
  description: Students will learn how to compose a range of critical media objects using web-authoring languages, text, sound, images, and video in proprietary and open-source software.
  # E.g., Spring 2013:
  term: Fall 2017
  instructor:
    name: Dr. Benjamin Miller
    office: CL 617-N 
    office_hours: t.b.d. or by appointment
    email: millerb@pitt.edu
    phone: 
    # No @ before your username; e.g., twitter, not @twitter
    twitter: benmiller314
